services:
  php:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
      dockerfile: .docker/php-fpm/Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      APP_KEY: ${APP_KEY}
    networks:
      - exemple-api
    depends_on:
      - mysql
    command: >
      sh -c "git config --global --add safe.directory /app && php-fpm"

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - ${NGINX_PORT_TWO}:${NGINX_PORT}
    depends_on:
      - php
    networks:
      - exemple-api

  redis:
    image: redis:alpine
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - exemple-api

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - exemple-api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - exemple-api

  npm:
    image: node:current-alpine
    container_name: npm
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      - exemple-api

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - exemple-api

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - ${PORTAINER_PORT}:${PORTAINER_PORT_TWO}
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/portainer:/data

networks:
  exemple-api:
    driver: bridge
